-- AlterTable
ALTER TABLE `media` MODIFY `type` ENUM('IMAGE', 'VIDEO', 'AUDIO') NOT NULL,
    MODIFY `status` ENUM('NEW', 'PENDING_UPLOAD', 'UPLOADING', 'UPLOADED', 'FAILED_UPLOAD', 'VALIDATING', 'REJECTED', 'READY', 'PROCESSING', 'READY_WITH_VARIANTS', 'FAILED_PROCESSING', 'DELETING', 'DELETED', 'PENDING', 'FAILED') NOT NULL DEFAULT 'PENDING';
