// Auto-generated by scripts/generateOpenapiTypes.mjs. Do not edit directly.
export interface paths {
  "/api/meta": {
    /** API meta */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MetaResponse"];
          };
        };
      };
    };
  };
  "/api/auth/signup": {
    /** Create a user and issue auth cookies */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthSignupBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AuthSignupResponse"];
          };
        };
      };
    };
  };
  "/api/auth/login": {
    /** Verify credentials and issue auth cookies */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthLoginBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AuthLoginResponse"];
          };
        };
      };
    };
  };
  "/api/auth/refresh": {
    /** Refresh access token */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/auth/logout": {
    /** Clear auth cookies */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/auth/me": {
    /** Return current user id and role */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AuthMeResponse"];
          };
        };
      };
    };
  };
  "/api/admin/jobs/history": {
    /** Get job run history */
    get: {
    };
  };
  "/api/admin/jobs/active": {
    /** Get active job runs */
    get: {
    };
  };
  "/api/admin/jobs/stats": {
    /** Get job statistics */
    get: {
    };
  };
  "/api/admin/jobs/enqueue": {
    /** Enqueue a job for execution */
    post: {
    };
  };
  "/api/admin/jobs/{jobRunId}/cancel": {
    /** Request job cancellation */
    post: {
      parameters: {
        path: {
          jobRunId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/admin/jobs/definitions": {
    /** Get available job definitions */
    get: {
    };
  };
  "/api/admin/jobs/cleanup-stalled": {
    /** Clean up stalled/orphaned jobs */
    post: {
    };
  };
  "/api/admin/jobs/{jobRunId}": {
    /** Get job run details */
    get: {
      parameters: {
        path: {
          jobRunId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/feed": {
    /** Homepage feed (posts + match suggestions) */
    get: {
      parameters: {
        query?: {
          cursorId?: components["schemas"]["Id"];
          take?: number;
          debug?: boolean;
          seed?: number;
          markSeen?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["FeedResponse"];
          };
        };
      };
    };
  };
  "/api/posts": {
    /** Create post */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["PostCreateBody"];
        };
      };
      responses: {
        /** @description OK */
        201: {
          content: {
            "application/json": components["schemas"]["PostCreateResponse"];
          };
        };
      };
    };
  };
  "/api/posts/{postId}": {
    /** Delete post */
    delete: {
      parameters: {
        path: {
          postId: components["schemas"]["Id"];
        };
      };
    };
    /** Update post */
    patch: {
      parameters: {
        path: {
          postId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PostPatchBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PostPatchResponse"];
          };
        };
      };
    };
  };
  "/api/posts/{postId}/media/{mediaId}": {
    /** Remove media from post */
    delete: {
      parameters: {
        path: {
          postId: components["schemas"]["Id"];
          mediaId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/posts/{postId}/save": {
    /** Save post */
    post: {
      parameters: {
        path: {
          postId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/comments": {
    /** List comments for a post */
    get: {
    };
    /** Create comment */
    post: {
    };
  };
  "/api/comments/{commentId}/replies": {
    /** Get replies for a comment */
    get: {
      parameters: {
        path: {
          commentId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/comments/{commentId}/like": {
    /** Like or unlike a comment */
    post: {
      parameters: {
        path: {
          commentId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/comments/{commentId}": {
    /** Delete a comment */
    delete: {
      parameters: {
        path: {
          commentId: components["schemas"]["Id"];
        };
      };
    };
    /** Edit a comment */
    patch: {
      parameters: {
        path: {
          commentId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/profiles/recommendations": {
    /** Get personalized profile recommendations based on MatchScore */
    get: {
    };
  };
  "/api/profiles/search": {
    /** Search users for @mention autocomplete */
    get: {
    };
  };
  "/api/profiles/advanced-search": {
    /** Advanced profile search with multiple filters */
    get: {
    };
  };
  "/api/profiles/search/traits": {
    /** Get available trait keys for search filters */
    get: {
    };
  };
  "/api/profiles/{userId}": {
    /** Get profile */
    get: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfileResponse"];
          };
        };
      };
    };
    /** Update own profile */
    patch: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProfilePatchBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfilePatchResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/{userId}/access-requests": {
    /** Request access to private profile content */
    post: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfileAccessResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/{userId}/access-grants": {
    /** Grant access to private profile content */
    post: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProfileAccessGrantBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfileAccessResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/{userId}/followers": {
    /** List followers (people following this profile) */
    get: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["FollowersResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/{userId}/following": {
    /** List following (people this profile follows) */
    get: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["FollowingResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/access-requests/{requestId}/approve": {
    /** Approve a follow request */
    post: {
      parameters: {
        path: {
          requestId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfileAccessResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/access-requests/{requestId}/deny": {
    /** Deny a follow request */
    post: {
      parameters: {
        path: {
          requestId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfileAccessResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/access-requests/{requestId}/cancel": {
    /** Cancel a follow request */
    post: {
      parameters: {
        path: {
          requestId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfileAccessResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/access-requests/{requestId}/revoke": {
    /** Revoke a follow */
    post: {
      parameters: {
        path: {
          requestId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ProfileAccessResponse"];
          };
        };
      };
    };
  };
  "/api/profiles/{userId}/rate": {
    /** Rate profile */
    post: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RateBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/likes": {
    /** List likes (profiles you liked, not yet matched) */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["LikesResponse"];
          };
        };
      };
    };
    /** Like / dislike / unlike */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SwipeBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SwipeResponse"];
          };
        };
      };
    };
  };
  "/api/matches": {
    /** List matches */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MatchListResponse"];
          };
        };
      };
    };
  };
  "/api/suggestions": {
    /** List match suggestions */
    get: {
      parameters: {
        query?: {
          cursorId?: components["schemas"]["Id"];
          take?: number;
          type?: "overall" | "ratings" | "ratings.attractive" | "ratings.smart" | "ratings.funny" | "ratings.interesting" | "ratings.fit" | "interests" | "nearby" | "new";
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SuggestionResponse"];
          };
        };
      };
    };
  };
  "/api/conversations/with/{userId}": {
    /** Get or create conversation with user */
    post: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/inbox": {
    /** Inbox conversations */
    get: {
      parameters: {
        query?: {
          cursorId?: components["schemas"]["Id"];
          take?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["InboxResponse"];
          };
        };
      };
    };
  };
  "/api/conversations/{conversationId}": {
    /** Get conversation */
    get: {
      parameters: {
        query?: {
          cursorId?: components["schemas"]["Id"];
          take?: number;
        };
        path: {
          conversationId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MessageListResponse"];
          };
        };
      };
    };
  };
  "/api/conversations/{conversationId}/delete": {
    /** Delete conversation for current user */
    post: {
      parameters: {
        path: {
          conversationId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/conversations/{conversationId}/messages": {
    /** Send message */
    post: {
      parameters: {
        path: {
          conversationId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["MessageSendBody"];
        };
      };
      responses: {
        /** @description OK */
        201: {
          content: {
            "application/json": components["schemas"]["MessageSendResponse"];
          };
        };
      };
    };
  };
  "/api/messages/{messageId}/read": {
    /** Mark read */
    post: {
      parameters: {
        path: {
          messageId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/quizzes/active": {
    /** Get active quiz */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["QuizResponse"];
          };
        };
      };
    };
  };
  "/api/quizzes/{quizId}": {
    /** Get quiz by id */
    get: {
      parameters: {
        path: {
          quizId: components["schemas"]["Id"];
        };
      };
    };
    /** Update quiz */
    patch: {
      parameters: {
        path: {
          quizId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["QuizUpdateBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["QuizUpdateResponse"];
          };
        };
      };
    };
  };
  "/api/quizzes": {
    /** List quizzes */
    get: {
    };
  };
  "/api/quizzes/tags": {
    /** List quiz tags */
    get: {
    };
  };
  "/api/quizzes/{quizId}/submit": {
    /** Submit quiz */
    post: {
      parameters: {
        path: {
          quizId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["QuizSubmitBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/quizzes/{quizId}/questions/{questionId}": {
    /** Update quiz question */
    patch: {
      parameters: {
        path: {
          quizId: components["schemas"]["Id"];
          questionId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["QuizQuestionPatchBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["QuizQuestionPatchResponse"];
          };
        };
      };
    };
  };
  "/api/quizzes/{quizId}/questions/{questionId}/options/{optionId}": {
    /** Update quiz option */
    patch: {
      parameters: {
        path: {
          quizId: components["schemas"]["Id"];
          questionId: components["schemas"]["Id"];
          optionId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["QuizOptionPatchBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["QuizOptionPatchResponse"];
          };
        };
      };
    };
  };
  "/api/quizzes/{quizId}/results": {
    /** Get quiz results with demographic comparisons */
    get: {
      parameters: {
        path: {
          quizId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/users/{userId}/block": {
    /** Block user */
    post: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/users/{userId}/report": {
    /** Report user */
    post: {
      parameters: {
        path: {
          userId: components["schemas"]["Id"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReportBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["OkResponse"];
          };
        };
      };
    };
  };
  "/api/media/upload": {
    /** Upload media (streaming) */
    post: {
      requestBody: {
        content: {
          "multipart/form-data": components["schemas"]["MediaUploadBody"];
        };
      };
      responses: {
        /** @description OK */
        201: {
          content: {
            "application/json": components["schemas"]["MediaUploadResponse"];
          };
        };
      };
    };
  };
  "/api/media/{mediaId}": {
    /** Get media */
    get: {
      parameters: {
        path: {
          mediaId: components["schemas"]["Id"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MediaResponse"];
          };
        };
      };
    };
    /** Delete media */
    delete: {
      parameters: {
        path: {
          mediaId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/interests/subjects": {
    /** List all interest subjects */
    get: {
    };
  };
  "/api/interests": {
    /** List interests with pagination */
    get: {
    };
  };
  "/api/interests/my": {
    /** Get user's selected interests */
    get: {
    };
  };
  "/api/interests/{interestId}/select": {
    /** Add interest to user */
    post: {
      parameters: {
        path: {
          interestId: components["schemas"]["Id"];
        };
      };
    };
    /** Remove interest from user */
    delete: {
      parameters: {
        path: {
          interestId: components["schemas"]["Id"];
        };
      };
    };
  };
  "/api/interests/search": {
    /** Search interests from text */
    post: {
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Id: string;
    OkResponse: {
      ok: boolean;
    };
    ErrorResponse: {
      error: string;
    };
    MetaResponse: {
      name: string;
      version: string;
    };
    AuthSignupBody: {
      email: string;
      password: string;
      rememberMe?: boolean;
    };
    AuthSignupResponse: {
      userId: components["schemas"]["Id"];
      email: string;
    };
    AuthLoginBody: {
      email: string;
      password: string;
      rememberMe?: boolean;
    };
    AuthLoginResponse: {
      userId: components["schemas"]["Id"];
    };
    AuthMeResponse: {
      userId: components["schemas"]["Id"];
      /** @enum {string} */
      role: "USER" | "ADMIN" | "SUPER_ADMIN";
    };
    /** @enum {string} */
    Visibility: "PUBLIC" | "PRIVATE";
    /** @enum {string} */
    AccessStatus: "NONE" | "PENDING" | "GRANTED" | "DENIED" | "REVOKED" | "CANCELED";
    /** @enum {string} */
    MediaType: "IMAGE" | "VIDEO" | "AUDIO";
    /** @enum {string} */
    MediaStatus: "PENDING" | "READY" | "FAILED";
    /** @enum {string} */
    Gender: "UNSPECIFIED" | "MALE" | "FEMALE" | "NONBINARY" | "OTHER";
    /** @enum {string} */
    DatingIntent: "UNSPECIFIED" | "FRIENDS" | "CASUAL" | "LONG_TERM" | "MARRIAGE";
    /** @enum {string} */
    MatchState: "ACTIVE" | "BLOCKED" | "CLOSED";
    /** @enum {string} */
    CompatibilityStatus: "READY" | "INSUFFICIENT_DATA";
    /** @enum {string} */
    SwipeAction: "LIKE" | "DISLIKE" | "UNLIKE";
    /** @enum {string} */
    ReportReason: "SPAM" | "HARASSMENT" | "IMPERSONATION" | "NUDITY" | "HATE" | "OTHER";
    Media: {
      id: components["schemas"]["Id"];
      type: components["schemas"]["MediaType"];
      url: string;
      thumbUrl?: string | null;
      width?: number | null;
      height?: number | null;
      durationSec?: number | null;
    };
    MediaUrls: {
      original: string;
      thumb?: string | null;
    };
    MediaUploadResponse: {
      mediaId: components["schemas"]["Id"];
      status: components["schemas"]["MediaStatus"];
      mimeType: string;
      urls: components["schemas"]["MediaUrls"];
    };
    MediaResponse: {
      mediaId: components["schemas"]["Id"];
      status: components["schemas"]["MediaStatus"];
      mimeType?: string | null;
      sizeBytes?: number | null;
      width?: number | null;
      height?: number | null;
      durationSec?: number | null;
      urls: components["schemas"]["MediaUrls"];
    };
    MediaUploadBody: {
      /** Format: binary */
      file: string;
    };
    PostMedia: {
      order: number;
      media: components["schemas"]["Media"];
    };
    FeedPost: {
      id: components["schemas"]["Id"];
      text?: string | null;
      /** Format: date-time */
      createdAt: string;
      presentation?: components["schemas"]["FeedPresentation"] | null;
      user: {
        id: components["schemas"]["Id"];
        profile?: ({
          displayName?: string | null;
        }) | null;
      };
      media: components["schemas"]["PostMedia"][];
    };
    FeedPresentation: {
      /** @enum {string} */
      mode: "single" | "mosaic" | "question" | "highlight";
      /** @enum {string|null} */
      accent?: "match" | "boost" | "new" | null;
    };
    FeedSuggestion: {
      userId: components["schemas"]["Id"];
      displayName?: string | null;
      bio?: string | null;
      locationText?: string | null;
      intent?: string | null;
      /** @enum {string|null} */
      source?: "match" | "suggested" | null;
      compatibility?: components["schemas"]["CompatibilitySummary"] | null;
      presentation?: components["schemas"]["FeedPresentation"] | null;
    };
    FeedQuestionOption: {
      id: components["schemas"]["Id"];
      label: string;
      value: string;
    };
    FeedQuestion: {
      id: components["schemas"]["Id"];
      quizId: components["schemas"]["Id"];
      quizTitle?: string | null;
      prompt: string;
      options: components["schemas"]["FeedQuestionOption"][];
      presentation?: components["schemas"]["FeedPresentation"] | null;
    };
    SuggestionProfile: ({
      displayName?: string | null;
      locationText?: string | null;
      intent?: string | null;
      avatarUrl?: string | null;
    }) | null;
    SuggestionItem: {
      userId: components["schemas"]["Id"];
      profile?: components["schemas"]["SuggestionProfile"];
      score: number;
      reasons?: {
        [key: string]: unknown;
      } | null;
      compatibility: components["schemas"]["CompatibilitySummary"] | null;
    };
    SuggestionResponse: {
      suggestions: components["schemas"]["SuggestionItem"][];
      nextCursorId: components["schemas"]["Id"] | null;
    };
    FeedItem: {
      /** @enum {string} */
      type: "post" | "suggestion" | "question";
      post?: components["schemas"]["FeedPost"] | null;
      suggestion?: components["schemas"]["FeedSuggestion"] | null;
      question?: components["schemas"]["FeedQuestion"] | null;
    };
    FeedDebug: {
      seed: number | null;
      candidates: {
        postIds: components["schemas"]["Id"][];
        suggestionUserIds: components["schemas"]["Id"][];
        questionIds?: components["schemas"]["Id"][];
        counts: {
          posts: number;
          suggestions: number;
          questions?: number;
        };
      };
      dedupe: {
        postDuplicates: number;
        suggestionDuplicates: number;
        questionDuplicates?: number;
        crossSourceRemoved: number;
      };
      seen: {
        windowHours: number;
        demotedPosts: number;
        demotedSuggestions: number;
      };
      ranking?: {
        sourceSequence?: string[];
        actorCounts?: {
          [key: string]: number;
        };
      } | null;
    };
    FeedResponse: {
      items: components["schemas"]["FeedItem"][];
      nextCursorId: components["schemas"]["Id"] | null;
      hasMorePosts: boolean;
      debug?: components["schemas"]["FeedDebug"] | null;
    };
    PostCreateBody: {
      text?: string | null;
      visibility?: components["schemas"]["Visibility"];
      mediaIds?: components["schemas"]["Id"][];
      targetUserId?: components["schemas"]["Id"];
    };
    PostCreateResponse: {
      id: components["schemas"]["Id"];
      /** Format: date-time */
      createdAt: string;
    };
    PostPatchBody: {
      text?: string | null;
      visibility?: components["schemas"]["Visibility"];
    };
    PostPatchResponse: {
      id: components["schemas"]["Id"];
      text?: string | null;
      visibility: components["schemas"]["Visibility"];
      /** Format: date-time */
      updatedAt: string;
    };
    ProfileTop5Item: {
      order: number;
      text: string;
    };
    ProfileTop5List: {
      id: components["schemas"]["Id"];
      title: string;
      /** Format: date-time */
      updatedAt: string;
      items: components["schemas"]["ProfileTop5Item"][];
    };
    Profile: {
      userId: components["schemas"]["Id"];
      displayName?: string | null;
      bio?: string | null;
      /** Format: date-time */
      birthdate?: string | null;
      locationText?: string | null;
      gender?: string | null;
      intent?: string | null;
      avatarUrl?: string | null;
      heroUrl?: string | null;
      isVisible: boolean;
      top5Lists: components["schemas"]["ProfileTop5List"][];
    };
    ProfilePost: {
      id: components["schemas"]["Id"];
      visibility: components["schemas"]["Visibility"];
      text?: string | null;
      /** Format: date-time */
      createdAt: string;
      media: components["schemas"]["PostMedia"][];
    };
    ProfileAccessInfo: {
      status: components["schemas"]["AccessStatus"];
      requestId?: components["schemas"]["Id"] | null;
      hasPrivatePosts: boolean;
      hasPrivateMedia: boolean;
    };
    ProfileRatingAvg: {
      attractive?: number | null;
      smart?: number | null;
      funny?: number | null;
      interesting?: number | null;
    };
    ProfileRatingMine: {
      attractive: number;
      smart: number;
      funny: number;
      interesting: number;
      /** Format: date-time */
      createdAt: string;
    };
    ProfileRatings: {
      count: number;
      avg: components["schemas"]["ProfileRatingAvg"];
      mine: components["schemas"]["ProfileRatingMine"] | null;
    };
    CompatibilitySummary: {
      score: number | null;
      status: components["schemas"]["CompatibilityStatus"];
    };
    ProfileResponse: {
      profile: components["schemas"]["Profile"] | null;
      posts: components["schemas"]["ProfilePost"][];
      access: components["schemas"]["ProfileAccessInfo"] | null;
      ratings: components["schemas"]["ProfileRatings"];
      compatibility: components["schemas"]["CompatibilitySummary"] | null;
    };
    ProfileAccessGrantBody: {
      viewerUserId: components["schemas"]["Id"];
    };
    ProfileAccessResponse: {
      status: components["schemas"]["AccessStatus"];
      requestId: components["schemas"]["Id"] | null;
    };
    FollowerItem: {
      requestId: components["schemas"]["Id"];
      userId: components["schemas"]["Id"];
      name: string;
      avatarUrl: string | null;
      status: components["schemas"]["AccessStatus"];
      /** Format: date-time */
      requestedAt: string;
      /** Format: date-time */
      updatedAt: string;
      compatibility: components["schemas"]["CompatibilitySummary"] | null;
    };
    FollowersResponse: {
      followers: components["schemas"]["FollowerItem"][];
    };
    FollowingResponse: {
      following: components["schemas"]["FollowerItem"][];
    };
    ProfilePatchBody: {
      displayName?: string | null;
      bio?: string | null;
      /** Format: date-time */
      birthdate?: string | null;
      locationText?: string | null;
      lat?: number | null;
      lng?: number | null;
      gender?: components["schemas"]["Gender"];
      intent?: components["schemas"]["DatingIntent"];
      isVisible?: boolean | null;
      avatarMediaId?: components["schemas"]["Id"] | null;
      heroMediaId?: components["schemas"]["Id"] | null;
    };
    ProfilePatchResponse: {
      userId: components["schemas"]["Id"];
      /** Format: date-time */
      updatedAt: string;
    };
    RateBody: {
      attractive: number;
      smart: number;
      funny: number;
      interesting: number;
    };
    SwipeBody: {
      toUserId: components["schemas"]["Id"];
      action: components["schemas"]["SwipeAction"];
    };
    SwipeResponse: {
      ok: boolean;
      matched?: boolean;
      matchId?: components["schemas"]["Id"] | null;
    };
    LikeProfile: ({
      displayName?: string | null;
      locationText?: string | null;
      intent?: string | null;
      avatarUrl?: string | null;
    }) | null;
    LikeItem: {
      id: components["schemas"]["Id"];
      userId: components["schemas"]["Id"];
      /** Format: date-time */
      likedAt: string;
      profile: components["schemas"]["LikeProfile"];
      compatibility: components["schemas"]["CompatibilitySummary"] | null;
    };
    LikesResponse: {
      likes: components["schemas"]["LikeItem"][];
    };
    MatchUserProfile: {
      displayName?: string | null;
      locationText?: string | null;
      intent?: string | null;
      avatarUrl?: string | null;
    };
    MatchUser: {
      id: components["schemas"]["Id"];
      profile?: components["schemas"]["MatchUserProfile"] | null;
      compatibility: components["schemas"]["CompatibilitySummary"] | null;
    };
    MatchItem: {
      id: components["schemas"]["Id"];
      userAId: components["schemas"]["Id"];
      userBId: components["schemas"]["Id"];
      /** Format: date-time */
      updatedAt: string;
      conversation?: {
        id: components["schemas"]["Id"];
      } | null;
      userA: components["schemas"]["MatchUser"];
      userB: components["schemas"]["MatchUser"];
    };
    MatchListResponse: {
      matches: components["schemas"]["MatchItem"][];
    };
    InboxUserProfile: {
      displayName?: string | null;
      avatarUrl?: string | null;
    };
    InboxUser: {
      id: components["schemas"]["Id"];
      profile?: components["schemas"]["InboxUserProfile"] | null;
      compatibility: components["schemas"]["CompatibilitySummary"] | null;
    };
    FollowRequestRef: {
      id: components["schemas"]["Id"];
      status: components["schemas"]["AccessStatus"];
    };
    InboxMessage: {
      id: components["schemas"]["Id"];
      body: string;
      /** Format: date-time */
      createdAt: string;
      senderId: components["schemas"]["Id"];
      isSystem: boolean;
      followRequest?: components["schemas"]["FollowRequestRef"] | null;
    };
    InboxConversation: {
      id: components["schemas"]["Id"];
      /** Format: date-time */
      updatedAt: string;
      otherUser: components["schemas"]["InboxUser"];
      lastMessage: components["schemas"]["InboxMessage"] | null;
      unreadCount: number;
    };
    InboxResponse: {
      conversations: components["schemas"]["InboxConversation"][];
      nextCursorId: components["schemas"]["Id"] | null;
    };
    MessageItem: {
      id: components["schemas"]["Id"];
      body: string;
      senderId: components["schemas"]["Id"];
      /** Format: date-time */
      createdAt: string;
      isSystem: boolean;
      followRequest?: components["schemas"]["FollowRequestRef"] | null;
    };
    MessageListResponse: {
      conversationId: components["schemas"]["Id"];
      messages: components["schemas"]["MessageItem"][];
      nextCursorId: components["schemas"]["Id"] | null;
    };
    MessageSendBody: {
      body: string;
    };
    MessageSendResponse: {
      id: components["schemas"]["Id"];
      /** Format: date-time */
      createdAt: string;
    };
    QuizOption: {
      id: components["schemas"]["Id"];
      label: string;
      value: string;
      order: number;
    };
    QuizQuestion: {
      id: components["schemas"]["Id"];
      prompt: string;
      order: number;
      options: components["schemas"]["QuizOption"][];
    };
    Quiz: {
      id: components["schemas"]["Id"];
      slug: string;
      title: string;
      questions: components["schemas"]["QuizQuestion"][];
    };
    QuizResponse: {
      quiz: components["schemas"]["Quiz"] | null;
    };
    QuizSubmitBody: {
      answers: {
        [key: string]: unknown;
      };
      scoreVec?: {
        [key: string]: unknown;
      } | null;
    };
    QuizUpdateBody: {
      title: string;
    };
    QuizUpdateResponse: {
      id: components["schemas"]["Id"];
      title: string;
      /** Format: date-time */
      updatedAt: string;
    };
    QuizQuestionPatchBody: {
      prompt: string;
    };
    QuizQuestionPatchResponse: {
      id: components["schemas"]["Id"];
      prompt: string;
    };
    QuizOptionPatchBody: {
      label: string;
    };
    QuizOptionPatchResponse: {
      id: components["schemas"]["Id"];
      label: string;
      value: string;
    };
    ReportBody: {
      reason: components["schemas"]["ReportReason"];
      details?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
