/* global process, console */
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS from 'openapi-typescript'

const __dirname = dirname(fileURLToPath(import.meta.url))
const frontendRoot = resolve(__dirname, '..')
const backendRoot = resolve(frontendRoot, '..', 'backend')
const tsxBin = process.platform === 'win32'
  ? resolve(backendRoot, 'node_modules', '.bin', 'tsx.cmd')
  : resolve(backendRoot, 'node_modules', '.bin', 'tsx')

const openapiEntry = resolve(backendRoot, 'src', 'lib', 'openapi', 'emitOpenApi.ts')
const outputPath = resolve(frontendRoot, 'src', 'api', 'openapi.ts')

const tsxCommand = process.platform === 'win32' ? 'cmd' : tsxBin
const tsxArgs = process.platform === 'win32'
  ? ['/c', tsxBin, openapiEntry]
  : [openapiEntry]

const raw = execFileSync(tsxCommand, tsxArgs, { cwd: backendRoot, encoding: 'utf8' })
const spec = JSON.parse(raw)

const types = await openapiTS(spec, {
  commentHeader: '// Auto-generated by scripts/generateOpenapiTypes.mjs. Do not edit directly.'
})

writeFileSync(outputPath, types)
console.log(`Wrote ${outputPath}`)
