/**
 * Generates TypeScript types from the backend OpenAPI specification.
 * 
 * This script:
 * 1. Runs the backend's emitOpenApi.ts to generate an OpenAPI JSON spec
 * 2. Converts the spec to TypeScript types using openapi-typescript
 * 3. Writes the types to src/api/openapi.ts
 * 
 * Note: The backend script imports the registry which may initialize Prisma.
 * If the database is not available, this script will timeout after 30 seconds.
 */

/* global process, console, setTimeout, clearTimeout */
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { existsSync, writeFileSync, readFileSync, unlinkSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS from 'openapi-typescript'

const execFileAsync = promisify(execFile)

const __dirname = dirname(fileURLToPath(import.meta.url))
const frontendRoot = resolve(__dirname, '..')
const repoRoot = resolve(frontendRoot, '..')
const backendRoot = resolve(repoRoot, 'backend')
const tsxBinBackend = process.platform === 'win32'
  ? resolve(backendRoot, 'node_modules', '.bin', 'tsx.cmd')
  : resolve(backendRoot, 'node_modules', '.bin', 'tsx')
const tsxBinRoot = process.platform === 'win32'
  ? resolve(repoRoot, 'node_modules', '.bin', 'tsx.cmd')
  : resolve(repoRoot, 'node_modules', '.bin', 'tsx')
const tsxBin = existsSync(tsxBinBackend) ? tsxBinBackend : tsxBinRoot

const openapiEntry = resolve(backendRoot, 'src', 'lib', 'openapi', 'emitOpenApi.ts')
const outputPath = resolve(frontendRoot, 'src', 'api', 'openapi.ts')
const specPath = resolve(backendRoot, 'openapi.json')

const tsxCommand = process.platform === 'win32' ? 'cmd' : tsxBin
const tsxArgs = process.platform === 'win32'
  ? ['/c', tsxBin, openapiEntry, specPath]
  : [openapiEntry, specPath]

const TIMEOUT_MS = 60000 // 60 seconds - TypeScript compilation and module loading can take time

console.log('Generating OpenAPI spec from backend...')
console.log(`Running: ${tsxCommand} ${tsxArgs.join(' ')}`)

try {
  // Write to file instead of stdout to avoid Windows pipe buffering issues
  // Prisma is now lazy-loaded, so it won't initialize during OpenAPI generation
  // The emitOpenApi script only reads route metadata and doesn't need database access
  const execPromise = execFileAsync(tsxCommand, tsxArgs, { cwd: backendRoot, encoding: 'utf8' })
  let timeoutTimer
  const timeoutPromise = new Promise((_, reject) => {
    timeoutTimer = setTimeout(() => {
      reject(new Error(`Timeout: Script took longer than ${TIMEOUT_MS}ms. This may indicate TypeScript compilation is slow or a module import is hanging.`))
    }, TIMEOUT_MS)
  })
  
  execPromise.finally(() => {
    if (timeoutTimer) clearTimeout(timeoutTimer)
  })
  
  const { stderr } = await Promise.race([execPromise, timeoutPromise])
  
  // Show stderr if there are any warnings or errors
  if (stderr && !stderr.includes('Warning')) {
    console.error('Backend stderr output:')
    console.error(stderr)
  }
  
  // Read the generated JSON file
  const raw = readFileSync(specPath, 'utf8')
  const spec = JSON.parse(raw)
  
  // Clean up temp file
  unlinkSync(specPath)
  
  // Generate TypeScript types
  const types = await openapiTS(spec, {
    commentHeader: '// Auto-generated by scripts/generateOpenapiTypes.mjs. Do not edit directly.'
  })
  
  writeFileSync(outputPath, types)
  console.log(`Wrote ${outputPath}`)
  console.log('Yay!')
  console.log('   1. Run TypeScript compiler to catch type errors')
  console.log('   2. Review api/adapters.ts for compatibility')
  console.log('   3. Check for new Api* types that need domain type equivalents in api/types.ts')
} catch (error) {
  // Clean up temp file on error
  if (existsSync(specPath)) {
    try {
      unlinkSync(specPath)
    } catch {
      // Ignore cleanup errors
    }
  }
  
  console.error('Failed to generate OpenAPI spec:')
  console.error(error.message)
  if (error.message.includes('Timeout')) {
    console.error('\nPossible causes:')
    console.error('  1. TypeScript compilation is taking longer than expected')
    console.error('  2. A module import is hanging (check for blocking operations)')
    console.error('  3. Database connection attempt (Prisma should be lazy-loaded)')
  }
  process.exit(1)
}